[HOTFIX] lib/vfs: Fix build error
The error was introduced by a4a56ddd674d8c206498995586019da93aec0b8e:

lib/vfs/smaky6fs.cc:259:53: error: no matching function for call to 'Path::Path(std::vector<std::__cxx11::basic_string<char> >::const_iterator, __gnu_cxx::__normal_iterator<const std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >)'
  259 |         Path parentPath(path.begin(), path.end() - 1);
      |                                                     ^

The new code requires a new Path ctor to be exposed, was probably forgotten.

Signed-off-by: Pavel Fedin <pavel_fedin@mail.ru>